export default {
  strm: '2247',
  classNumber: '63151',
  courseId: '104171',
  courseOfferNumber: '1',
  sessionCode: 'A',
  classSection: '2001',
  subject: 'CSE',
  catalogNumber: '100',
  schedulePrint: true,
  description: 'Prin of Programming with C++',
  classStatusCode: 'A',
  classStatusDescription: 'Active',
  startDate: 1724310000000,
  endDate: 1728630000000,
  locationCode: 'ASUONLINE',
  locationDescription: 'ASU Online',
  campusCode: 'TEMPE',
  courseComponent: 'LEC',
  courseComponentDescription: 'Lecture',
  gradedComponent: true,
  associatedClass: 2001,
  instructorEdit: 'N',
  courseTopicTitle: null,
  promodShell: false,
  offeredByDepartmentAcadOrgCode: 'CCOMPENG',
  offeredByCollegeAcadOrgCode: 'CES',
  instructionModeCode: 'OL',
  combinedSectionsId: null,
  displayTitle: 'Prin of Programming with C++',
  enrollmentCapacity: 200,
  finalGradeRosterPosted: false,
  classNotes: ['Class notes 1', 'Class notes 2'],
  meetings: [
    {
      meetingNumber: 1,
      instructors: [
        {
          schedulePrint: true,
          instructorRole: 'PI',
          assignSequence: 1,
          firstName: 'John',
          lastName: 'Doe',
          iSearchUrl: 'https://webapp4.asu.edu/directory/person/1234567890',
        },
      ],
      startDate: 1729062000000,
      endDate: 1733468400000,
      startTime: 25200000,
      endTime: 28800000,
      meetDays: ['M', 'W', 'F'],
      facilityId: 'CDN60',
      facilityLocationCode: 'TEMPE',
      facilityRoom: '60',
      facilityDescription: 'Clg Of Dsgn North 60 (Tempe)',
      buildingCode: 'CDN',
      buildingDescription: 'Design North',
      buildingCountry: 'USA',
      buildingAddress1: '',
      buildingAddress2: '',
      buildingAddress3: '',
      buildingAddress4: '',
      buildingCity: '',
      buildingState: '',
      buildingPostal: '',
      buildingCampus: 'TEMPE',
    },
  ],
};
